export const productCategory = [
  {
    id: Math.random(),
    type: 1,
    title: 'Đồ chơi - Mẹ & Bé',
    desc: 'Vật dụng đồ dùng cho mẹ và bé giá tốt nhất » Tiki.vn',
    image: require('../../assets/images/category/1.jpg'),
  },
  {
    id: Math.random(),
    type: 2,
    title: 'Làm Đẹp - Sức Khỏe',
    desc: 'Làm đẹp - Sức khỏe - nhiều sản phẩm | Mua giá rẻ hơn tại Tiki.vn',
    image: require('../../assets/images/category/2.jpg'),
  },
  {
    id: Math.random(),
    type: 3,
    title: 'Điện Thoại - Máy Tính Bảng',
    desc:
      'Điện thoại, Máy tính bảng | Chính hãng, Giá rẻ hơn, Trả góp 0% tại Tiki.vn',
    image: require('../../assets/images/category/3.jpg'),
  },
  {
    id: Math.random(),
    type: 4,
    title: 'Thời Trang',
    desc: 'Mua Sắm Quần Áo, Thời Trang Hàng Hiệu Online » Tiki.vn: Thời Trang',
    image: require('../../assets/images/category/5.jpg'),
  },
  {
    id: Math.random(),
    type: 5,
    title: 'Điện Tử - Điện Lạnh',
    desc:
      'Điện Tử - Điện Lạnh: Tivi, Audio, Tủ lạnh, Máy giặt, Máy lạnh Tại Tiki',
    image: require('../../assets/images/category/6.png'),
  },
  {
    id: Math.random(),
    type: 6,
    title: 'Nhà Cửa - Đời Sống',
    desc: 'Nhà cửa đời sống » Mua đồ dùng gia đình Giá Rẻ tại Tiki.vn',
    image: require('../../assets/images/category/7.jpg'),
  },
  {
    id: Math.random(),
    type: 7,
    title: 'Hàng Quốc Tế',
    desc: 'Hàng Quốc Tế',
    image: require('../../assets/images/category/8.jpg'),
  },
  {
    id: Math.random(),
    type: 8,
    title: 'Bách Hóa Online',
    desc: 'Mua online các mặt hàng bách hóa giá tốt | Tiki.vn',
    image: require('../../assets/images/category/9.jpg'),
  },
  {
    id: Math.random(),
    type: 9,
    title: 'Thiết Bị - Phụ Kiện Số',
    desc: 'Mua online các mặt hàng Thiết Bị - Phụ Kiện Số giá tốt | Tiki.vn',
    image: require('../../assets/images/category/10.jpg'),
  },
  {
    id: Math.random(),
    type: 10,
    title: 'Voucher - Dịch vụ',
    desc: 'Mua online các mặt hàng Voucher - Dịch vụ giá tốt | Tiki.vn',
    image: require('../../assets/images/category/11.jpg'),
  },
  {
    id: Math.random(),
    type: 11,
    title: 'Ô tô - Xe máy',
    desc: 'Mua online các mặt hàng Ô tô - Xe máy giá tốt | Tiki.vn',
    image: require('../../assets/images/category/12.jpg'),
  },
  {
    id: Math.random(),
    type: 12,
    title: 'Nhà sách Tiki',
    desc: 'Mua online các mặt hàng Nhà sách Tiki giá tốt | Tiki.vn',
    image: require('../../assets/images/category/13.jpg'),
  },
  {
    id: Math.random(),
    type: 13,
    title: 'Laptop -Tivi - Máy vi tính',
    desc:
      'Mua online các mặt hàng Laptop -Tivi - Máy vi tính giá tốt | Tiki.vn',
    image: require('../../assets/images/category/14.png'),
  },
  {
    id: Math.random(),
    type: 14,
    title: 'Thể Thao - Dã ngoại',
    desc: 'Mua online các mặt hàng Thể Thao - Dã ngoại giá tốt | Tiki.vn',
    image: require('../../assets/images/category/15.png'),
  },
  {
    id: Math.random(),
    type: 15,
    title: 'Máy ảnh - Máy quay phim',
    desc: 'Máy ảnh - Máy quay phim giá tốt | Tiki.vn',
    image: require('../../assets/images/category/16.jpg'),
  },
];
