const AppStyles = {
  colors: {
    accentColor: '#0084ff',
    inactiveGreyColor: '#626262',
    lightGreyColor: '#7f8c8d',
    separator: '#bdc3c7',
    white: 'white',
    black: 'black',
    grey: 'grey',
    green: 'green',
    onlineGreen: '#2ecc71',
    lightWhite: '#f9f9f9',
    LIGHT_GRAY: '#F1F1F1',
    GRAY: '#dddddd',
    BLACK_GRAY: '#333',
    ORANGE: '#eb4e2e',
    SILVER: '#BDBDBD',
    BLUE: '#2E3952',
    TEXT_COLOR: '#454f63',
    SUB_TITLE: '#9DA5B8',
    BG_BUTTON_INACTIVE: '#F4F4F6',
    BG_BUTTON_ACTIVE: '#3497FD',
    TEXT_BTN_INACTIVE: '#7D88A1',
    PLACEHOLDER_TEXT: '#B4BBC9',
    ERROR: '#ff424e',
    TRANSPARENT: 'transparent',
    primary: '#555CC4',
    primaryLight: '#829BF8',
    primaryGradientStart: '#4f44b6',
    primaryGradientEnd: '#4f44b6',
    secondaryGradientStart: '#FF1358',
    secondaryGradientEnd: '#FF1358',
    profileGradientStart: '#54CBF6',
    profileGradientEnd: '#49D2D0',
    secondary: '#FF1358',
    gray: '#5f5f5f',
    darkGray: '#4d4d4d',
    lightGray: '#9b9b9b',
    blue: '#5A81F7',
    bluish: '#F1F1F7',
    yellow: '#ffc247',
    lightGrey: '#999999',
    lightGreyBold: '#D9D8DB',
    PRIMARY_BOLD: '#434BC8',
    lightBlueTiki: '#1ba8ff',
    lightBlack: '#393939',
  },
  fonts: {
    FONT_REGULAR: 'Roboto-Regular',
    FONT_MEDIUM: 'Roboto-Medium',
    FONT_LIGHT: 'Roboto-Light',
    FONT_THIN: 'Roboto-Thin',
    primaryLight: 'Lato-Light',
    primaryRegular: 'Lato-Regular',
    primaryBold: 'Lato-Bold',
    primarySemiBold: 'Lato-SemiBold',
  },
};

export default AppStyles;
